### ISSUE TITLE
Changing templates for beginning and completed messages

### ISSUE THREAD

**Issue by vlm---** [serilog-metrics/serilog-metrics#10]
I tried to use custom templates for beginning and completed messages, but it seems that `TimedOperation` is not respecting them in terms that it keeps rendering same properties in same order as in default templates.
After investigating in code, it is obvious that the `GeneratePropertyBag` method is not working with the current template and it assumes that all generated properties are always wanted and in predefined order.

**Comment by mivano** [comment]
That is correct. The properties are not configurable in that sense. In that case you need to override the methods and provide your own implementation (and return this implementation using your own method extension). 

What kind of customization are you after?

**Comment by vlm---** [comment]
I'm already attaching custom EventId and some other properties so I wanted to left out `TimedOperationDescription` which is useless in my case and `TimedOperationElapsed` to save some space in log files. But it is nothing I can't live without.
