### ISSUE TITLE
Support for stopping timed operations in different scopes

### ISSUE THREAD

**Issue by wshirey** [serilog-metrics/serilog-metrics#13]
If you wanted to time an event that was restricted to class scope but crossed method boundaries, it's not entirely evident that calling Dispose() on the object returned from BeginTimedOperation() stops the timed operation.

What about composing a new ITimingMeasure interface that implements IDisposable and IMeasure and has a contract method called

```
interface ITimingMeasure : IDisposable, IMeasure 
{
    void Complete(bool write);
}
```

**Comment by mivano** [comment]
Thanks for the PR. I was working on something called progress. See here https://github.com/serilog-metrics/serilog-metrics/pull/6 
In theory almost ready to go. Although not directly the same as the timing measure, it has a more explicit finish/fail etc interface. Is this something that can help you?

**Comment by wshirey** [comment]
I think that will suffice. Thanks.
