### ISSUE TITLE
Doesn't work with the last version of serilog

### ISSUE THREAD

**Issue by ogamaniuk** [serilog-metrics/serilog-metrics#15]
Could not load file or assembly 'Serilog, Version=1.4.0.0, Culture=neutral, PublicKeyToken=24c2f752a8e58a10' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

**Comment by nblumhardt** [comment]
Thanks for the report, I think we need a package update in this repo.

**Comment by mivano** [comment]
@nblumhardt you know what to do with this issue? Just update the nuget packages inside the solution?

**Comment by nblumhardt** [comment]
Hi @mivano - yes, that's all AFAIK :+1:

**Comment by mivano** [comment]
Thanks, I updated the packages (https://github.com/serilog-metrics/serilog-metrics/pull/16).
