### ISSUE TITLE
template parameter ignored when using counter with resolution

### ISSUE THREAD

**Issue by zivni** [serilog-metrics/serilog-metrics#17]
when specifying resolution and template in the `CountOperation` method,  the template is ignored.
In the code that checks `resolution.HasValue` there is an overwrite to the template parameter.
There should be a check to see if the template paramter was given by the method user. i.e. 

```
if (resolution.HasValue)          
{
       if(template == DefaultCountTemplate)
                template = DefaultResolutionCountTemplate;
        counterResolution = resolution.Value;
}
```

**Comment by mivano** [comment]
Thanks for the report. Fixed.
