### ISSUE TITLE
Support metrics for async operations (Tasks)

### ISSUE THREAD

**Issue by pardahlman** [serilog-metrics/serilog-metrics#18]
I'm writing a lot of `async` methods, where I return Tasks without `awaiting` them.

``` csharp
internal Task ExampleMethodAsync(Foo foo)
{ 
    return _service
        .PerformSomethingAsync(foo)
        .ContinueWith(barTask =>
        {
            _anotherService.PerformChainedAsync(barTask.Result)
        });
}
```

I still want to get some metrics from the task, like execution time, but I don't want to await the call just to achieve that. I think it would be nice if  `serilog-metrics` provided an async API. Here's an example of how it could look like

``` csharp
internal Task ExampleMethodAsync(Foo foo)
{ 
    var fooTask = _service
        .PerformSomethingAsync(foo)
        .ContinueWith(barTask =>
        {
            _anotherService.PerformChainedAsync(barTask.Result)
        });
    Logger.LogTaskExecutionTime(fooTask, foo => $"Value of prop is: {foo.Prop}.");
    return stateTask;
}
```

Where the second argument is `Func<TTaskResult,string>` that is evaluated after the task (of type `Task<TTaskResult>`) has completed.

I have some local code for this that could be used, and I'm willing to help. Just wanted to check if there are any ideas as for how the api should look like.

**Comment by mivano** [comment]
I m certainly open to include async support in this library. Makes a lot of sense to be able to support this too. I do not have a lot of experience with async, so curious to your proposal/code.
