### ISSUE TITLE
IMeterMeasure should inherit from IDisposable

### ISSUE THREAD

**Issue by kashifshaikh** [serilog-metrics/serilog-metrics#19]
MeterMeasure class must be disposed, so when creating a meter measure through serilogger, the MeterOperation extension returns IMeterMeasure which doesn't inherit from IDisposable. 

So
(using meterOperation = (Logger.MeterOperation)) {

}

won't work unless you cast like so,
(using meterOperation = (MeterOperation)(Logger.MeterOperation)) {

}

**Comment by mivano** [comment]
Sorry for the late response. Why do you want to dispose? You need to create a meter and then you can reuse it during your application when needed.

``` csharp
var meter = logger.MeterOperation ("Errors");

meter.Mark ();
Thread.Sleep (200);
meter.Mark ();

meter.Write ();
```

Disposing Serilog logger itself should only happen at the end of your application.
