### ISSUE TITLE
Package update to version 2.0.1 fails

### ISSUE THREAD

**Issue by mleyb** [serilog-metrics/serilog-metrics#21]
Hi - we've tried to update to the 2.0.1 package release in nuget, but the update fails with this error:

"Severity   Code    Description Project File    Line    Suppression State
Error       Failed to add reference. The package 'SerilogMetrics' tried to add a framework reference to 'System.Collections.Concurrent' which was not found in the GAC. This is possibly a bug in the package. Please contact the package owners for assistance.            0"

We've got Serilog package version 2.2.1 installed. Any ideas?

**Comment by mleyb** [comment]
Any info on this? Is this an issue?

**Comment by nblumhardt** [comment]
Hi, thanks for getting in touch. I'm reasonably sure all .NET 4.5 machines should have System.Collections.Concurrent - might be an issue with the machine. Have you tried it on a second machine?

Cheers,
Nick

**Comment by hknga1** [comment]
I got the issue here

**Comment by mleyb** [comment]
I've tried upgrading 3 separate solutions (1 @ .NET 4.5.1 and 2 @ .NET 4.6.1) with projects that currently target Serilogmetrics 1.0.34 on two separate machines, and I get the same issue. In all 3 solutions we're targeting Serilog 2.3.0.

Installing Serilog 2.3.0 & Serilogmetrics 2.0.1 into a brand new solution works fine. An explicit reference to System.Collections.Concurrent can be see in the "References" list for the project

**Comment by mleyb** [comment]
Righto - I've narrowed this down. It seems that I can't install SerilogMetrics 2.0.1 into any project which also has these already installed:

"Microsoft.Bcl" version="1.1.10"
"Microsoft.Bcl.Build" version="1.0.21"
"Microsoft.Net.Http" version="2.2.29"

My reproduction details:
- create new project in VS2015
- install-package Microsoft.Net.Http
- install-package Serilog
- install-package Serilogmetrics

install-package : Failed to add reference. The package 'SerilogMetrics' tried to add a framework reference to 'System.Collections.Concurrent' which was not 
found in the GAC. This is possibly a bug in the package. Please contact the package owners for assistance.

If i install the packages in order Serilog -> Serilogmetrics -> Microsoft.Net.Http everything seems OK ?

**Comment by nblumhardt** [comment]
@mleyb very interesting!

**Comment by djcameron** [comment]
We're seeing this behavior too, and we can't get it to install at all.

**Comment by nblumhardt** [comment]
Googled around, I believe we're hitting this:

https://github.com/NuGet/Home/issues/1855

Could someone please verify that manually adding a reference to _System.Collections.Concurrent_ before installing the package allows the installation to succeed? Cheers!

**Comment by djcameron** [comment]
I had to manually add both System.Collections.Concurrent and System.Threading

**Comment by hastarin** [comment]
@nblumhardt Manually installing the NuGet package does not allow installation to proceed.

**Comment by nblumhardt** [comment]
PR'd the fix; in .NET 4.5 these are in mscorlib (they're only facades in the modern surface area).

FWIW I think adding a Microsoft.Bcl.Build dependency might have sorted this out, but just removing the references does a clean job of it :-)

@mivano once this is through CI, any reason to hold back on pushing it to master? Cheers!

**Comment by mivano** [comment]
Thanks @nblumhardt 

Sorry for the troubles and time before I could dive into this. Too much other stuff going around. 

I hope this fixes the issue.

**Comment by nblumhardt** [comment]
Thanks @mivano :+1:
