### ISSUE TITLE
Ways to omit the "Beginning operation" entry

### ISSUE THREAD

**Issue by pardahlman** [serilog-metrics/serilog-metrics#24]
We use `TimedOperation` on several places in our applications to measure performance. The log entries from the `BeginningOperationTemplate` fills our logs with "_Beginning operation..._". One request can result in up to 20 of these entries!

It takes up considerable space in our elastic index and makes it cumbersome to analyze the logs, as we first need to add filters etc.

It would be great if there where a way for us to omit the log entry altogether. My first approach was to pass in `null` to as template for `beginningMessage`, but as the template parameter itself is optional, the null value is replaced by the default value.

Another, different, approach would be to extend the constructor of `TimedOperation` to include an optional bool `bool omitBeginLogs= false` or perhaps add an optional parameter for log level on that particular entry. Then again, I don't know if that's the best approach as the interface for the logger is already pretty cluttered.  Any ideas?

I'd be happy to contribute if we decide upon a good approach.

Keep up the good job!

**Comment by nblumhardt** [comment]
Apologies for the possibly-unhelpful alternative, but you might find [Serilog Timings](https://nblumhardt.com/2016/04/serilog-timings/) useful for this - it's main goal (vs. Serilog Metrics, which is more full-featured) is to combine all the output from an operation into a single event as you described. HTH.

**Comment by pardahlman** [comment]
@nblumhardt looks very interesting! Thanks for pointing me in this direction!

**Comment by mivano** [comment]
I think the tip from @nblumhardt is a very good one. Making more extensions to the current library makes it more complex. 
The textual part is also not that interesting indeed. If you work with for example a Sink like Elasticsearch, you can filter on the message template and use the duration fields to report on/graph with.

**Comment by stephenpatten** [comment]
@nblumhardt 

Does the recommendation still stand today, that is to use the lighter weight Timings for single line timings?

**Comment by bwedding** [comment]
Of course you can just clone the repo, make the message anything you want an build your own Nuget package to use locally.
