### ISSUE TITLE
Counter Add(int value) Method

### ISSUE THREAD

**Issue by SilentBlueD666** [serilog-metrics/serilog-metrics#25]
Looking at counter measure and I understand it increments by one, but could support be added to add to the counter more than one i.e. 'Add(int value)'?

I have found that in a few places I have a list of work done and I have to loop and increment the counter which feels very dumb ;)

The AtomicLong class already uses, the interlocked class using add method,
https://docs.microsoft.com/en-us/dotnet/api/system.threading.interlocked.add?view=netframework-4.7.2

Therefore would just need to add method to 'ICounterMeasure' and 'CounterMeasure'

**Comment by mivano** [comment]
Would be a nice addition. Care for a pull request?

**Comment by SilentBlueD666** [comment]
Cool, be happy to :)

**Comment by SilentBlueD666** [comment]
I just cloned and made a branch, but I don't have permission to push the branch to remote (opps), do you want me to Fork and then do a PR, or is it OK to get branch creation permission. ;)

**Comment by mivano** [comment]
I think the neatest solution is indeed to fork and do a PR back from your branch to this branch.

**Comment by SilentBlueD666** [comment]
Have now created pull request, have a look and let me know what you think or any changes you need me to make, I had to update the project to VS2017 and also update the Nuget pack 'Microsoft.NET.Test.Sdk' to version 15.0.0 on the test project to get it to build, not sure if this will cause you problems?

**Comment by mivano** [comment]
Thanks for the addition. I changed/updated the build system a bit, so took some tries to get it all working, but there is a new package here: https://www.nuget.org/packages/SerilogMetrics/2.1.0

**Comment by SilentBlueD666** [comment]
That's great :)
