### ISSUE TITLE
Scope of serilog-metrics

### ISSUE THREAD

**Issue by StephenHynes7** [serilog-metrics/serilog-metrics#7]
Just curious about the scope of this package, using the term "metrics" makes me think that it's quite broad and isn't just limited to timers and what not.

Do you envision the capturing of System Metrics to be in the scope of this package?

**Comment by mivano** [comment]
We started this as a Serilog.Extras.Timing package containing a simple disposable block that records start and end time. However it was inspired by the Metrics.net library. So gradually more metrics were introduced; gauges, meters, counters etc. So measures that will generate a metric that can be stored in the logging system of Serilog. If you just use the default output of Serilog like the console than you will not gain a lot, but combined with the structured logging frameworks as ElasticSearch, RavenDB, MongoDB etc, you can reason about the metrics generated. 

So the scope; I see this library as a helper framework for performing common measuring of tasks, actions, operations etc while using the Serilog infrastructure for storing the results. 

System metrics; this library can be used for both web and non web, so the definition of system metrics can differ. Although I can imagine that extensions are possible that report of performance counters for example using this library.

Does this answer your question?

**Comment by StephenHynes7** [comment]
Yep that's great thanks :)

-----Original Message-----
